version: '3.1'

services:
        ftps:
            image: vsftpd
            build:
                context: ./ftps/
            volumes:
                - ftps:/var/ftp
            ports:
                    - "21:21"
                    - "21000-21010:21000-21010"
            networks:
                - backend
                - frontend
        nginx:
            image: nginx
            build:
                context: ./nginx/
                args:
                  WORDPRESS_EXTERNAL_NAME : 'localhost'
                  PHPMYADMIN_DNS_NAME : 'phpmyadmin'
            ports:
                    - "80:80"
                    - "443:443"
            networks:
                - backend
                - frontend
        wordpress:
            image: wordpress
            build:
                context: ./wordpress/
            ports:
                    - "5050:5050"
            volumes:
              - wordpress:/var/www/html
            environment:
              WORDPRESS_DB_HOST: 'mysql:3306'
              WORDPRESS_DB_USER: 'wordpress'
              WORDPRESS_DB_PASSWORD: 'password'
              WORDPRESS_DB_NAME: 'wordpress'
              URL: 'localhost:5050'
              ADMIN_USER: 'admin'
              ADMIN_EMAIL: 'admin@example.org'
              ADMIN_PASSWORD: 'password'
              EDITOR_USER: 'editor'
              EDITOR_EMAIL: 'editor@example.org'
              EDITOR_PASSWORD: 'password'
              AUTHOR_USER: 'author'
              AUTHOR_EMAIL: 'author@example.org'
              AUTHOR_PASSWORD: 'password'
              TITLE: 'ft_services'
            networks:
                - frontend
                - backend
        phpmyadmin:
            image: phpmyadmin
            build:
                context: ./phpmyadmin
            ports:
                    - "5000:5000"
            environment:
              WORDPRESS_DB_HOST: 'mysql:3306'
              WORDPRESS_DB_USER: 'wordpress'
              WORDPRESS_DB_PASSWORD: 'password'
            networks:
                - frontend
                - backend
        mysql:
            image: mysqld
            build:
                context: ./mysql
            volumes:
                - mysql:/data
            environment:
                MYSQL_DATABASE: wordpress
                MYSQL_USER: wordpress
                MYSQL_PASSWORD: password
                MYSQL_RANDOM_ROOT_PASSWORD: '1'
            ports:
                - "3306:3306"
            networks:
                - backend
        influxdb:
            image: influxdb
            build:
                context: ./influxdb
            volumes:
                - influxdb:/root/.influxdb
            networks:
                - backend
        grafana:
            image: grafana
            build:
                context: ./grafana
            ports:
                - "3000:3000"
            networks:
                - backend
                - frontend
        prometheus:
            image: prometheus
            build:
                context: ./prometheus
            ports:
                - "9090:9090"
            networks:
                - backend
                - frontend

networks:
    frontend:
    backend:
volumes:
    ftps:
    influxdb:
    mysql:
    wordpress:
