version: '3.1'

services:
        ftps:
                image: vsftpd
                build:
                    context: ./ftps/
                    dockerfile: Dockerfile
                ports:
                        - 21:21
                        - 21000-21010:21000-21010
        wordpress:
                image: wordpress
                build:
                    context: ./wordpress/
                ports:
                        - 5050:443
                environment:
                  WORDPRESS_DB_HOST: mysql
                  WORDPRESS_DB_USER: user
                  WORDPRESS_DB_PASSWORD: pass
                  WORDPRESS_DB_NAME: wordpress
                #volumes:
                  #- wordpress:/var/www/html
        mysql:
                image: mysql:5.7
                environment:
                  MYSQL_DATABASE: wordpress
                  MYSQL_USER: wordpress
                  MYSQL_PASSWORD: password
                  MYSQL_RANDOM_ROOT_PASSWORD: '1'
                #volumes:
                  #- db:/var/lib/mysql

#volumes:
        #wordpress:
        #db:

