version: '3.1'

services:
        ftps:
                image: vsftpd
                build:
                        context: ./ftps/
                        dockerfile: Dockerfile
                ports:
                        - 21:21
                        - 21000-21010:21000-21010
        wordpress:
                image: wordpress
                ports:
                        - 5050:80
                environment:
                  WORDPRESS_DB_HOST: mysql
                  WORDPRESS_DB_USER: user
                  WORDPRESS_DB_PASSWORD: pass
                  WORDPRESS_DB_NAME: wordpress
                volumes:
                  - wordpress:/var/www/html
        mysql:
                image: mysql:5.7
                environment:
                  MYSQL_DATABASE: wordpress
                  MYSQL_USER: user
                  MYSQL_PASSWORD: pass
                  MYSQL_RANDOM_ROOT_PASSWORD: '1'
                volumes:
                  - db:/var/lib/mysql

volumes:
        wordpress:
        db:

