version: '3.1'

services:
        #ftps:
                #image: vsftpd
                #build:
                    #context: ./ftps/
                    #dockerfile: Dockerfile
                #ports:
                        #- 21:21
                        #- 21000-21010:21000-21010
        #wordpress:
                #image: wordpress
                #build:
                    #context: ./wordpress/
                    #args:
                      #WORDPRESS_DB_HOST: 'mysql:3306'
                      #WORDPRESS_DB_USER: 'wordpress'
                      #WORDPRESS_DB_PASSWORD: 'password'
                      #WORDPRESS_DB_NAME: 'wordpress'
                #ports:
                        #- 5050:443
                #volumes:
                  #- wordpress:/var/www/html
        #mysql:
                #image: mysqld
                #build:
                    #context: ./mysql
                #volumes:
                    #- mysql-data:/data
                #environment:
                    #MYSQL_DATABASE: wordpress
                    #MYSQL_USER: wordpress
                    #MYSQL_PASSWORD: password
                    #MYSQL_RANDOM_ROOT_PASSWORD: '1'
        influxdb:
            image: influxdb
            build:
                context: ./influxdb
            #volumes:
                #- influxdb:/var/lib/influxdb
        grafana:
            image: grafana
            build:
                context: ./grafana
            ports:
                - 3000:3000
                - 9090:9090
        #prometheus:
            #image: prometheus
            #build:
                #context: ./prometheus
            #ports:
                #- 9090:9090


volumes:
    mysql-data:
    wordpress:
    influxdb:

