apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
      metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql:3306"
        - name: WORDPRESS_DB_USER
          value: "wordpress"
        - name: WORDPRESS_DB_PASSWORD
          value: "password"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        - name: URL
          value: "%IP%:5050"
        - name: ADMIN_USER
          value: "admin"
        - name: ADMIN_EMAIL
          value: "admin@example.org"
        - name: ADMIN_PASSWORD
          value: "password"
        - name: EDITOR_USER
          value: "editor"
        - name: EDITOR_EMAIL
          value: "editor@example.org"
        - name: EDITOR_PASSWORD
          value: "password"
        - name: AUTHOR_USER
          value: "author"
        - name: AUTHOR_EMAIL
          value: "author@example.org"
        - name: AUTHOR_PASSWORD
          value: "password"
        - name: TITLE
          value: "ft_services"
        ports:
            - containerPort: 5050
