version: '3'

services:
        ftps:
                image: vsftpd
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - 21:21
                        - 21000-21010:21000-21010
