version: '3.1'

services:
        mysql:
                image: mysql
                build:
                    context: ./
                volumes:
                  - toto:/data
                environment:
                  MYSQL_DATABASE: wordpress
                  MYSQL_USER: wordpress
                  MYSQL_PASSWORD: password
                  MYSQL_RANDOM_ROOT_PASSWORD: '1'
                #volumes:
                  #- db:/var/lib/mysql

volumes:
  toto:
        #wordpress:
        #db:

